# Enable these to see SQL statements (DEBUG) and their parameters (TRACE)
#logging:
#  level:
#    org:
#      springframework:
#        jdbc:
#          core:
#            JdbcTemplate: DEBUG
#            StatementCreatorUtils: TRACE
