version: '3'
services:
  basilisk-db:
    environment:
      - POSTGRES_USER=basilisk
    image: postgres
    ports:
      - 5432:5432

  basilisk-service:
    build:
      context: .
      args:
        APP_JAR: basilisk-service/build/libs/basilisk-service-0.jar
        GRADLE_VERSION: 5.2.1
        JAVA_VERSION: 11.0.2
    depends_on:
      - basilisk-db
    environment:
      - SPRING_BOOT_ADMIN_CLIENT=http://app:8080/admin
      - SPRING_DATASOURCE_URL=jdbc:postgresql://basilisk-db/basilisk?user=basilisk
    ports:
      - 8080:8080
