version: '3'
services:
  app:
    build:
      context: .
      args:
        APP_JAR: basilisk-service/build/libs/basilisk-service-0.jar
        GRADLE_VERSION: 5.2.1
        JAVA_VERSION: 11.0.2
    depends_on:
      - "db"
    ports:
      - "8080:8080"

  db:
    environment:
      POSTGRES_USER: basilisk
    image: postgres
    ports:
      - "5432:5432"
