basilisk:
  extra-word: 'Uncle Bob'

logging:
  level:
    root: 'WARN'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

server:
  error:
    include-exception: true
    include-stacktrace: on_trace_param

spring:
  application:
    name: 'basilisk'
  data:
    rest:
      detection-strategy: annotated
  main:
    banner-mode: 'off'
