basilisk:
  extra-word: 'Uncle Bob'

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: 'basilisk'
  main:
    banner-mode: 'off'

---

spring:
  profiles:
    active: 'alternative'

basilisk:
  extra-word: 'Margaret Hamilton'

---

spring:
  profiles:
    active: 'broken'

basilisk:
  extra-word: 'F'
