# Enable these to see SQL statements (DEBUG) and their parameters (TRACE)
logging:
  level:
    #    org.springframework.jdbc.core:
    #      JdbcTemplate: DEBUG
    #      StatementCreatorUtils: TRACE
    hm.binkley.basilisk: INFO
    root: WARN

spring:
  datasource:
    platform: postgresql
    url: 'jdbc:postgresql:basilisk?user=basilisk'
  main:
    banner-mode: 'off'
