basilisk:
  extra-word: 'Uncle Bob'
  nested:
    number: 3
  overlapped:
    endpoint-base: 'http://some-where/else'

logging:
  level:
    root: 'WARN'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

server:
  error:
    include-stacktrace: never

spring:
  application:
    name: 'basilisk'
  data:
    rest:
      base-path: '/data'
      detection-strategy: annotated
  datasource:
    platform: 'h2' # Ex: use 'postgresql' for prod; 'h2' for in-memory
    url: jdbc:h2:mem:;MODE=PostgreSQL
  main:
    banner-mode: 'off'

swagger:
  ui:
    description: 'A demonstration Spring Boot program'
    contact:
      name: 'Brian Oxley'
      url: 'https://github.com/binkley/basilisk'
      email: 'binkley@alumni.rice.edu'
    licence: 'Public Domain'
    license-url: 'https://github.com/binkley/basilisk/blob/master/LICENSE.md'
    title: 'Basilisk'
    version: '0'

---

spring:
  profiles:
    active: 'test-basilisk-properties'

basilisk:
  extra-word: 'Margaret Hamilton'
