# Because this is in a different Spring active profile based on the file name,
# it _overrides_ the main `application-test.yml`: no need to copy over the whole thing

basilisk:
  extra-word: 'Margaret Hamilton'

flora:
  daily-special: 'POTATO'
