basilisk:
  extra-word: 'Uncle Bob'
  nested:
    number: 3
  overlapped:
    endpoint-base: http://some-where/else

feign:
  client:
    config:
      default:
        logger-level: 'FULL'

flora:
  daily-special: 'EGGS'
  nested:
    number: 3
  overlapped:
    endpoint-base: http://some-where/else

logbook:
  exclude:
    - /actuator
    - /actuator/health
    - /actuator/info
    - /admin/instances
  format:
    style: 'http'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

server:
  error:
    include-stacktrace: never

spring:
  boot:
    admin:
      client:
        url: http://localhost:8080/admin
      context-path: /admin
      ui:
        title: Basilisk
  data:
    rest:
      base-path: /data
      detection-strategy: annotated
  datasource:
    platform: postgresql
    url: 'jdbc:postgresql:basilisk?user=basilisk'
  jackson:
    # TODO: Millis showing up anyways
    date-format: "yyyy-MM-dd'T'HH:mm:ssX"
    property-naming-strategy: 'KEBAB_CASE'
    time-zone: 'UTC'
  main:
    banner-mode: 'OFF'
  output:
    ansi:
      enabled: 'ALWAYS'

swagger:
  ui:
    description: 'A demonstration Spring Boot program'
    contact:
      name: 'Brian Oxley'
      url: https://github.com/binkley/basilisk
      email: binkley@alumni.rice.edu
    licence: 'Public Domain'
    license-url: https://github.com/binkley/basilisk/blob/master/LICENSE.md
    title: Basilisk
    version: 0

---

logbook:
  format:
    style: 'json'

logging:
  level:
    x.loggy: DEBUG
    root: INFO

spring:
  output:
    ansi:
      enabled: 'NEVER'
  profiles: json
